on:
  push:
    branches:
      - master  # Only run when changes are pushed to master
      
name: 🚀 Deploy to Production server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: wwwroot/   # Only upload the wwwroot folder
        exclude: |
          **/.git*
          **/.git*/**
        timeout: 180000
    - name: 🔥 Purge Cloudflare Cache
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CFZONEID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CFAPITOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
